# Generated by Django 5.2.16 on 2026-08-10 12:57

import apps.content.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContentPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=120, unique=True, verbose_name="页面地址"
                    ),
                ),
                ("title", models.CharField(max_length=160, verbose_name="标题")),
                ("summary", models.TextField(blank=True, verbose_name="摘要")),
                ("body", models.TextField(blank=True, verbose_name="正文")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="content/pages/%Y/%m/",
                        validators=[apps.content.validators.validate_content_image],
                        verbose_name="页面图片",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="排序"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="公开"
                    ),
                ),
                (
                    "legacy_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, unique=True, verbose_name="旧站栏目 ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "内容页面",
                "verbose_name_plural": "内容页面",
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="HeroSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=160, verbose_name="标题"),
                ),
                (
                    "subtitle",
                    models.CharField(blank=True, max_length=255, verbose_name="副标题"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="content/slides/%Y/%m/",
                        validators=[apps.content.validators.validate_content_image],
                        verbose_name="图片",
                    ),
                ),
                (
                    "link_url",
                    models.CharField(blank=True, max_length=255, verbose_name="链接"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="排序"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="启用"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "首页轮播图",
                "verbose_name_plural": "首页轮播图",
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="巧侬", max_length=100, verbose_name="网站名称"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        upload_to="content/site/%Y/%m/",
                        validators=[apps.content.validators.validate_content_image],
                        verbose_name="Logo",
                    ),
                ),
                (
                    "home_title",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="首页标题"
                    ),
                ),
                (
                    "home_subtitle",
                    models.TextField(blank=True, verbose_name="首页副标题"),
                ),
                (
                    "home_intro_title",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="首页介绍标题"
                    ),
                ),
                (
                    "home_intro_body",
                    models.TextField(blank=True, verbose_name="首页介绍正文"),
                ),
                (
                    "home_intro_image",
                    models.ImageField(
                        blank=True,
                        upload_to="content/site/%Y/%m/",
                        validators=[apps.content.validators.validate_content_image],
                        verbose_name="首页介绍图片",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="公司名称"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="联系电话"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="联系邮箱"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="联系地址"
                    ),
                ),
                (
                    "social_qr",
                    models.ImageField(
                        blank=True,
                        upload_to="content/site/%Y/%m/",
                        validators=[apps.content.validators.validate_content_image],
                        verbose_name="社交二维码",
                    ),
                ),
                (
                    "footer_text",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="页脚补充文字"
                    ),
                ),
                (
                    "icp_number",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="ICP备案号"
                    ),
                ),
                (
                    "icp_url",
                    models.URLField(
                        blank=True,
                        default="https://beian.miit.gov.cn/",
                        verbose_name="备案链接",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "网站设置",
                "verbose_name_plural": "网站设置",
            },
        ),
    ]
