# Generated by Django 5.2.16 on 2026-08-10 12:50

import apps.catalog.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名称")),
                (
                    "slug",
                    models.SlugField(
                        max_length=120, unique=True, verbose_name="页面地址"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="简介")),
                (
                    "banner",
                    models.ImageField(
                        blank=True,
                        upload_to="catalog/categories/%Y/%m/",
                        validators=[apps.catalog.validators.validate_catalog_image],
                        verbose_name="栏目图",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="排序"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="启用"
                    ),
                ),
                (
                    "legacy_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, unique=True, verbose_name="旧站分类 ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="catalog.category",
                        verbose_name="上级分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "产品分类",
                "verbose_name_plural": "产品分类",
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160, verbose_name="名称")),
                (
                    "slug",
                    models.SlugField(
                        max_length=180, unique=True, verbose_name="页面地址"
                    ),
                ),
                (
                    "tag",
                    models.CharField(blank=True, max_length=80, verbose_name="标签"),
                ),
                ("summary", models.TextField(blank=True, verbose_name="摘要")),
                (
                    "specification",
                    models.CharField(blank=True, max_length=200, verbose_name="规格"),
                ),
                ("description", models.TextField(blank=True, verbose_name="详情正文")),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        upload_to="catalog/products/%Y/%m/",
                        validators=[apps.catalog.validators.validate_catalog_image],
                        verbose_name="封面图",
                    ),
                ),
                (
                    "hover_image",
                    models.ImageField(
                        blank=True,
                        upload_to="catalog/products/%Y/%m/",
                        validators=[apps.catalog.validators.validate_catalog_image],
                        verbose_name="悬停图",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="排序"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="首页推荐"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="上架"
                    ),
                ),
                (
                    "legacy_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, unique=True, verbose_name="旧站产品 ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.category",
                        verbose_name="所属分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "产品",
                "verbose_name_plural": "产品",
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="catalog/products/%Y/%m/",
                        validators=[apps.catalog.validators.validate_catalog_image],
                        verbose_name="图片",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="替代文字"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="排序"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.product",
                        verbose_name="产品",
                    ),
                ),
            ],
            options={
                "verbose_name": "产品图片",
                "verbose_name_plural": "产品图片",
                "ordering": ("sort_order", "id"),
            },
        ),
    ]
